// <auto-generated />
namespace AcunMedyaRestaurantly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig1categoryproductrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1categoryproductrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202502041039282_mig1categoryproductrelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
