// <auto-generated />
namespace AcunMedyaRestaurantly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig2_createadminn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig2_createadminn));
        
        string IMigrationMetadata.Id
        {
            get { return "202502181649412_mig2_createadminn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
